---
- name: Install package dependencies.
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Check if {{ oc_client_install_path }}/oc exists
  stat:
    path: "{{ oc_client_install_path }}/oc"
  register: oc_file_stat

- name: Check for oc_file_stat
  ansible.builtin.debug:
    msg: "Variable oc_file_stat contains: {{ oc_file_stat }}"

- name: Download oc client tool for {{ oc_client_version }} OpenShift Version
  ansible.builtin.get_url:
    url: "{{ oc_client_download_url }}/{{ oc_client_version }}/openshift-client-linux.tar.gz"
    dest: /tmp/oc-linux.tar.gz
  register: oc_download_bundle
  when: "not oc_file_stat.stat.exists"

- name: Extract oc-linux.tar.gz into /tmp/
  when: oc_download_bundle.changed
  ansible.builtin.unarchive:
    src: /tmp/oc-linux.tar.gz
    dest: /tmp
    copy: false
  register: oc_unarchive_download_bundle

- name: Copy oc binary with owner and permissions to {{ oc_client_install_path }}
  become: true
  ansible.builtin.copy:
    src: /tmp/oc
    dest: "{{ oc_client_install_path }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  when: oc_unarchive_download_bundle.changed

- name: Copy kubectl binary with owner and permissions to {{ oc_client_install_path }}
  become: true
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: "{{ oc_client_install_path }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  when: oc_unarchive_download_bundle.changed

- name: Remove file /tmp/oc-linux.tar.gz
  when: oc_download_bundle.changed
  ansible.builtin.file:
    path: /tmp/oc-linux.tar.gz
    state: absent

- name: Remove file /tmp/README.md
  when: oc_unarchive_download_bundle.changed
  ansible.builtin.file:
    path: /tmp/README.md
    state: absent

- name: Remove file /tmp/oc
  when: oc_unarchive_download_bundle.changed
  ansible.builtin.file:
    path: /tmp/oc
    state: absent

- name: Remove file /tmp/kubectl
  when: oc_unarchive_download_bundle.changed
  ansible.builtin.file:
    path: /tmp/kubectl
    state: absent
